### ISSUE TITLE
After typing in Jalali, it will be converted to Gregorian

### ISSUE THREAD

**Issue by HamedSiaban** [masoudit/antd-jalali-plus#4]
There is 2 ways to fill the input:
1. Use the popper and select the year, month and day -> This works good for now. :heavy_check_mark: 
2. Start typing the date manually in `YYYY/MM/DD` or  `YYYY-MM-DD`  format -> issue is here. :bug:   

Now the second approach works fine if you type the date in Gregorian. When you enter the last character, inside it will change it to Jalali and updates the value.
But when you enter the input in Jalali date, after entering the last character, it will change into something else. (I suspect the reason is it will try to convert it into Jalali again)

Here is the Image presentation:
(Consider today date -> 2025-05-07 | 1403-02-18)
[Screencast from 2024-05-07 19-25-41.webm](https://github.com/masoudit/antd-jalali/assets/83172266/cb5cd530-7443-466b-b48c-a1506090986f)

**Comment by hamidrezaghanbari** [comment]
Dear @HamedSiaban, please give me more detail about your situation. is this happen when your calendar is adjusted with jalali and then when you typing it converts to georgian date? if it is possible to you please send image and more details.

**Comment by HamedSiaban** [comment]
@hamidrezaghanbari sure.
I updated the description as thorough and clear as I could. Please ask if anything is unclear.
