### ISSUE TITLE
RangePicker header has rtl issue

### ISSUE THREAD

**Issue by mhoseini967** [masoudit/antd-jalali-plus#6]
in antd: 5.17.2 and antd-jalali-plus: v1.4.x Range Picker header has RTL problem.

![Screenshot 2024-05-14 202312](https://github.com/masoudit/antd-jalali/assets/40181520/b604c4a7-ddbe-4115-97d4-5f24611aea2c)

i fixed by overwrite css:

.ant-picker-panel-layout
.ant-picker-panels {
  direction: rtl !important;
}

**Comment by hamidrezaghanbari** [comment]
Dear @mhoseini967 thank you for your point, but this problem still exist and we need more general way to fix this, because suppose you have multi language project which support jalali and georgian date picker in that case your `direction: rtl !important` wouldn't work.
